#!/bin/bash
( echo A && echo B ) || ( echo C && echo D )
echo A && ( echo B || echo C ) && echo D
echo sup || ( echo hello || echo salutations )
( echo sup || echo hello ) || echo salutations
echo hello || ( echo sup || echo salutations )
mkdir places && ( ls && echo rome )
ls; mkdir recipes && ( test -e /home/csmajs/jjime038/src/rshell/src/recipes && echo worked )
( mkdir speeches && ls ) || echo oops
mkdir begining && ( mkdir middle && ( mkdir end || echo no ending ) || echo no middle ) || echo no story
mkdir ending?; ( ( mkdir good && ls ) || ( mkdir bad && ls ) )
exit
